const degreeTitles = [
  // Bachelor's Degrees
  "Bachelor of Science (BSc)",
  "Bachelor of Arts (BA)",
  "Bachelor of Commerce (BCom)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Computer Science (BCS)",
  "Bachelor of Engineering (BEng)",
  "Bachelor of Technology (BTech)",
  "Bachelor of Fine Arts (BFA)",
  "Bachelor of Architecture (BArch)",
  "Bachelor of Design (BDes)",
  "Bachelor of Education (BEd)",
  "Bachelor of Laws (LLB)",
  "Bachelor of Medicine, Bachelor of Surgery (MBBS)",
  "Bachelor of Dental Surgery (BDS)",
  "Bachelor of Pharmacy (BPharm)",
  "Bachelor of Social Work (BSW)",
  "Bachelor of Agricultural Science (BSc Agri)",
  "Bachelor of Nursing (BN)",
  "Bachelor of Public Administration (BPA)",
  "Bachelor of Information Technology (BIT)",
  "Bachelor of Communication and Media Studies",
  "Bachelor of Environmental Science",
  "Bachelor of Political Science",
  "Bachelor of Statistics",
  "Bachelor of Actuarial Science",
  "Bachelor of Hospitality Management",
  "Bachelor of Tourism and Travel Management",
  "Bachelor of Culinary Arts",
  "Bachelor of Fashion Design",
  "Bachelor of Interior Design",
  "Bachelor of Urban Planning",
  "Bachelor of Library and Information Science",
  "Bachelor of International Relations",
  "Bachelor of Psychology",
  "Bachelor of Sociology",
  "Bachelor of Criminology",
  "Bachelor of Public Health (BPH)",
  "Bachelor of Veterinary Science (BVSc)",
  "Bachelor of Biomedical Science",
  "Bachelor of Biotechnology",

  // Master's Degrees
  "Master of Science (MSc)",
  "Master of Arts (MA)",
  "Master of Commerce (MCom)",
  "Master of Business Administration (MBA)",
  "Master of Computer Science (MCS)",
  "Master of Engineering (MEng)",
  "Master of Technology (MTech)",
  "Master of Fine Arts (MFA)",
  "Master of Architecture (MArch)",
  "Master of Design (MDes)",
  "Master of Education (MEd)",
  "Master of Laws (LLM)",
  "Master of Public Administration (MPA)",
  "Master of Public Health (MPH)",
  "Master of Pharmacy (MPharm)",
  "Master of Social Work (MSW)",
  "Master of Agricultural Science (MSc Agri)",
  "Master of Nursing (MN)",
  "Master of Information Technology (MIT)",
  "Master of Philosophy (MPhil)",
  "Master of Data Science",
  "Master of Artificial Intelligence",
  "Master of Cybersecurity",
  "Master of Project Management",
  "Master of Supply Chain Management",
  "Master of Environmental Science",
  "Master of International Relations",
  "Master of Economics",
  "Master of Finance",
  "Master of Marketing",
  "Master of Human Resource Management",
  "Master of Urban Planning",
  "Master of Political Science",
  "Master of Statistics",
  "Master of Actuarial Science",
  "Master of Biotechnology",
  "Master of Biomedical Science",
  "Master of Veterinary Science",

  // Doctoral Degrees
  "Doctor of Philosophy (PhD)",
  "Doctor of Business Administration (DBA)",
  "Doctor of Medicine (MD)",
  "Doctor of Dental Surgery (DDS)",
  "Doctor of Education (EdD)",
  "Doctor of Pharmacy (PharmD)",
  "Doctor of Veterinary Medicine (DVM)",
  "Doctor of Public Health (DrPH)",
  "Doctor of Engineering (DEng)",
  "Doctor of Laws (LLD)",

  // Diplomas, Associates & Professional
  "Higher National Diploma (HND)",
  "Associate Degree in Science",
  "Associate Degree in Arts",
  "Associate Degree in Business",
  "Postgraduate Diploma (PGDip)",
  "Graduate Diploma in Education",
  "Chartered Accountant (CA)",
  "Certified Public Accountant (CPA)",
  "Chartered Financial Analyst (CFA)",
  "Project Management Professional (PMP)",
  "Six Sigma Certification",
  "AWS Certified Solutions Architect",
  "Microsoft Certified Azure Solutions Architect",
  "Google Cloud Professional Architect",
  "None"
];

export default degreeTitles;
