const functionalAreas = [
  "Software Development",
  "Data Science / AI-ML",
  "DevOps / SRE / Cloud",
  "Cybersecurity",
  "QA / Testing (Software)",
  "Product Management",
  "Project Management",
  "UI/UX / Design",
  "Marketing / Growth",
  "Sales / Business Development",
  "HR / Recruitment",
  "Finance / Accounting",
  "Customer Service / Support",
  "Operations / Admin",
  "Supply Chain / Logistics / Procurement",
  "Production / Manufacturing",
  "Quality / HSE (Manufacturing)",
  "Maintenance / Repair (Technical)",
  "Engineering (Non-Software)",
  "Real Estate / Construction",
  "Architecture / Interior Design",
  "Telecom / Networking",
  "Banking / Insurance",
  "Healthcare",
  "Education / Training",
  "Legal / Compliance",
  "Content / Writing / Editing",
  "Creative / Media / Video",
  "Data Entry / Back Office",
  "Retail / Store Operations",
  "Hospitality / Travel",
  "Research / R&D",
  "Public Sector / Government",
  "NGO / Social Impact",
  "Pharma / Biotech",
  "Agriculture / Food Processing",
  "Not mentioned"
];

export default functionalAreas;
