const functionalAreas = [
  "Accounting & Finance",
  "Administration",
  "Advertising",
  "Architecture",
  "Art & Design",
  "Banking",
  "Business Development",
  "Computer Networking",
  "Creative Design",
  "Customer Support",
  "Data Entry",
  "Education & Training",
  "Engineering",
  "Healthcare",
  "Human Resources",
  "Information Technology",
  "Legal",
  "Logistics & Supply Chain",
  "Marketing",
  "Media & Communications",
  "Operations",
  "Product Management",
  "Project Management",
  "Public Relations",
  "Quality Assurance",
  "Research & Development",
  "Sales",
  "Software Development",
  "Strategy & Planning",
  "Technical Support",
  "Writing & Content",
  "Other"
];

export default functionalAreas;
