const industries = [
  "IT / Software & Services",
  "Internet / E-commerce",
  "Telecom / ISP",
  "Media / Advertising / PR",
  "Consulting / Professional Services",
  "Legal Services",
  "Banking / Financial Services",
  "Insurance",
  "Fintech / Payments",
  "Healthcare / Hospitals",
  "Pharmaceuticals / Biotech",
  "Medical Devices",
  "Education / EdTech",
  "Government / Public Sector",
  "NGO / Non-profit",
  "Manufacturing (General)",
  "Manufacturing — Textiles / Apparel",
  "Manufacturing — Food & Beverage",
  "Manufacturing — Chemicals / Fertilizers / Plastics",
  "Manufacturing — Automotive / Auto Parts",
  "Manufacturing — Electronics / Electrical",
  "Manufacturing — Furniture / Wood",
  "Manufacturing — Cement / Steel / Metals",
  "Oil & Gas / Energy / Power",
  "Mining / Minerals",
  "Construction / Real Estate / Developers",
  "Architecture / Interior Design",
  "Utilities / Water / Waste",
  "Retail / FMCG / Consumer Goods",
  "Logistics / Transportation / Warehousing",
  "Hospitality / Travel / Tourism",
  "Agriculture / Agritech / Livestock",
  "Not mentioned"
];

export default industries;
