const pakistanCities = [
  "Abbottabad",
  "Ahmedpur East",
  "Ali Pur",
  "Arifwala",
  "Attock",
  "Awaran",
  "Badin",
  "Bahawalnagar",
  "Bahawalpur",
  "Bannu",
  "Barkhan",
  "Batkhela",
  "Bhakkar",
  "Bhalwal",
  "Bhakkar",
  "Burewala",
  "Chakwal",
  "Chaman",
  "Charsadda",
  "Chiniot",
  "Chishtian",
  "Dadu",
  "Daska",
  "Dera Ghazi Khan",
  "Dera Ismail Khan",
  "Faisalabad",
  "Ghotki",
  "Gujranwala",
  "Gujrat",
  "Gwadar",
  "Hafizabad",
  "Hangu",
  "Haripur",
  "Hyderabad",
  "Islamabad",
  "Jacobabad",
  "Jafarabad",
  "Jalalpur Jattan",
  "Jaranwala",
  "Jhang",
  "Jhelum",
  "Kalat",
  "Kamalia",
  "Karachi",
  "Kasur",
  "Kashmore",
  "Khanewal",
  "Kharian",
  "Khushab",
  "Khuzdar",
  "Kohat",
  "Kot Addu",
  "Kotli",
  "Lahore",
  "Larkana",
  "Layyah",
  "Lodhran",
  "Mandi Bahauddin",
  "Mardan",
  "Mian Channu",
  "Mianwali",
  "Mirpur",
  "Mirpur Khas",
  "Multan",
  "Muzaffarabad",
  "Muzaffargarh",
  "Nawabshah",
  "Nowshera",
  "Okara",
  "Pakpattan",
  "Peshawar",
  "Quetta",
  "Rahim Yar Khan",
  "Rajanpur",
  "Rawalpindi",
  "Sadiqabad",
  "Sahiwal",
  "Sanghar",
  "Sargodha",
  "Sheikhupura",
  "Shikarpur",
  "Sialkot",
  "Sibi",
  "Sukkur",
  "Swabi",
  "Swat",
  "Tando Adam",
  "Tando Allahyar",
  "Tando Muhammad Khan",
  "Tank",
  "Toba Tek Singh",
  "Vehari",
  "Wah Cantonment",
  "Zhob",
  "Ziarat"
];

export default pakistanCities;
